### ISSUE TITLE
setup uses directory name instead of extension name

### ISSUE THREAD

**Issue by ctaggart** [Azure/azure-cli-dev-tools#113]
I'm adding Azure Pipelines support in https://github.com/virtustream/azure-vmware-virtustream-cli-extension/pull/1 and I cam across what may have been a cause for https://github.com/Azure/azure-cli-dev-tools/issues/92. The name in `azdev setup -r $PWD -e name` ends up working if it is the directory name, not the extension name. 🐛 

I was able to work around it in Azure Pipeline [with this](https://github.com/virtustream/azure-vmware-virtustream-cli-extension/blob/ad3725e98fc272323c0f960a81f681599364aa3b/azure-pipelines.yml#L28-L38):
``` yaml
- script: |
    pipenv run azdev setup -r $PWD
  displayName: 'Install azdev'

- script: |
    pipenv run azdev extension list
    # pipenv run azdev extension add azure-vmware-virtustream-cli-extension
    # I do not understand why azdev is using the directory name.
    nm=${PWD##*/}
    pipenv run azdev extension add $nm
  displayName: 'Add extension'
```
